dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

script:
  - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 cmake . -DENABLE_COVERAGE=1
  - cmake --build . -- -j2
  - ctest --verbose -j2
  - wget https://raw.githubusercontent.com/pokemongo-dev-contrib/pokemongo-game-master/master/versions/latest/GAME_MASTER.json
  # missing output file
  - ./src/DbGen/PoGoDbGen GAME_MASTER.json || true
  # successful run
  - ./src/DbGen/PoGoDbGen GAME_MASTER.json test.h
  # invalid input file:
  - ./src/DbGen/PoGoDbGen test.h test2.h || true
  - ./src/Cli/PoGoCmpCli sort atk -i gen1 --descending
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-8
