image:
  - Visual Studio 2015
clone_folder: c:\projects\source
build_script:
- cmd: >-
    mkdir build

    cd build

    cmake c:\projects\source -G "Visual Studio 14 2015 Win64"

    cmake --build . --config "RelWithDebInfo"

test_script:
- cmd: ctest --verbose -C RelWithDebInfo