#include "../PoGoCmp/PoGoCmp.h"

#include <iostream>
#include <fstream>
#include <string>

int main(int argc, char **argv)
{
    std::cout << argc << std::endl;
    if (argc < 2) {
        std::cerr << "Output path missing. Usage: PoGoCmpDbGen <outputhPath>\n";
        return EXIT_FAILURE;
    }

    std::string outputPath{argv[1] };
    std::ofstream dbFile{ outputPath };
    if (!dbFile.is_open()) {
        std::cerr << "Failed to open " << outputPath << "\n";
        return EXIT_FAILURE;
    }

    dbFile <<
R"(// This file is generated by PoGoCmpDbGen.
#pragma once

struct PoGoCmpDb
{
    int test{0};
};
)";

}
